Repository PHS-TSA/wizards-in-calculus, pull requests merged in 2024-02, with the labels that each got.

#7 Remove whitespace and update comments
  NumberOne.gd
  RotationPoint.gd
  wizard.gd
Labels: chore

#8 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: chore

#11 Add sky
  node_2d.tscn
Labels: enhancement

#10 Updated Version with New Features
  NumberBalls/Ball_Sprites/0-removebg-preview.png
  NumberBalls/Ball_Sprites/0-removebg-preview.png.import
  NumberBalls/Ball_Sprites/1-removebg-preview.png
  NumberBalls/Ball_Sprites/1-removebg-preview.png.import
  NumberBalls/Ball_Sprites/2-removebg-preview.png
  NumberBalls/Ball_Sprites/2-removebg-preview.png.import
  NumberBalls/Ball_Sprites/3-removebg-preview.png
  NumberBalls/Ball_Sprites/3-removebg-preview.png.import
  NumberBalls/Ball_Sprites/4-removebg-preview.png
  NumberBalls/Ball_Sprites/4-removebg-preview.png.import
  NumberBalls/Ball_Sprites/5-removebg-preview.png
  NumberBalls/Ball_Sprites/5-removebg-preview.png.import
  NumberBalls/Ball_Sprites/6-removebg-preview.png
  NumberBalls/Ball_Sprites/6-removebg-preview.png.import
  NumberBalls/Ball_Sprites/7-removebg-preview.png
  NumberBalls/Ball_Sprites/7-removebg-preview.png.import
  NumberBalls/Ball_Sprites/8-removebg-preview.png
  NumberBalls/Ball_Sprites/8-removebg-preview.png.import
  NumberBalls/Ball_Sprites/9-removebg-preview.png
  NumberBalls/Ball_Sprites/9-removebg-preview.png.import
  NumberBalls/NumberOne.gd
  NumberBalls/NumberOne.tscn
  NumberBalls/NumberTwo.gd
  NumberBalls/NumberTwo.tscn
  NumberOne.tscn
  RotationPoint.gd
  Sprites/Types-of-rocks-schist-0721-removebg-preview.png
  Sprites/Types-of-rocks-schist-0721-removebg-preview.png.import
  nod6CA7.tmp
  nod7369.tmp
  nodD917.tmp
  node_2d.tscn
  rock.gd
  rock.tscn
Labels: enhancement

#13 Hitbox
  wizard.tscn
Labels: enhancement

#44 Add Heads Up Display
  game/characters/wizard/wizard.gd
  game/characters/wizard/wizard.tscn
  game/components/heads_up.gd
  game/components/heads_up.tscn
  game/levels/1.tscn
  game/levels/tutorial.tscn
  game/menus/game_over/game_over.tscn
  game/scenes/anti_math_juice/anti_math_juice.gd
  game/spawnables/rock/rock.gd
  game/styles/hud_box.tres
Labels: bug, enhancement

#54 Add Quick Math
  game/characters/wizard/wizard.gd
  game/levels/1.tscn
  game/spawnables/number/number.gd
  game/spawnables/number/number.tscn
  game/spawnables/quick_math/quick_math.gd
  game/spawnables/quick_math/quick_math.tscn
Labels: enhancement

#55 Use Signals for Quick Math
  game/characters/wizard/wizard.gd
  game/levels/1.tscn
  game/spawnables/number/number.gd
  game/spawnables/quick_math/quick_math.gd
  game/spawnables/quick_math/quick_math.tscn
Labels: chore
